version: '3.1'

services:
  oracle-tracker:
    hostname: oracle-tracker
    image: registry.cn-hangzhou.aliyuncs.com/helowin/oracle_11g
    container_name: oracle-tracker
    restart: always
    ports:
    - "1521:1521"
