version: '3.1'

services:
  mysql-db:
    image: nacos/nacos-mysql:5.7
    container_name: mysql5.7-docker
    env_file:
      - .env
    volumes:
      - "${MYSQL_DIR}/data:/var/lib/mysql"
      - "${MYSQL_DIR}/config:/etc/mysql/conf.d"
    restart: always
    ports:
      - "3307:3306"