version: '3.1'

services:

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-docker
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - "${RABBITMQ_DIR}:/var/lib/rabbitmq"
    restart: always
    hostname: myRabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"